@echo off
echo Starting AssuRisk Backend...
cd C:\Projects\Compliance_Product\Backend
echo Activating Virtual Environment...
call venv\Scripts\activate.bat
echo Starting Uvicorn Server...
python -m uvicorn app.main:app --reload --port 8000
pause
