-- PostgreSQL Migration Script for Multitenancy (RLS)
-- Generated by Antigravity

-- 1. Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Define Tables to Migrate
-- List: 
-- users, frameworks, controls, control_mappings, policies, evidence, assessments, documents,
-- master_templates, context_issues, interested_parties, scope_documents, processes, sub_processes, 
-- process_control_mapping, requirement_master, requirement_status, compliance_settings

-- Helper Macro-like block (Manual expansion for safety)

-- ==========================================
-- TABLE: users
-- ==========================================
-- Note: You might need to cast existing string tenant_ids to UUID or reset them.
-- Assuming table exists.
ALTER TABLE users ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON users;
CREATE POLICY tenant_isolation_policy ON users
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: frameworks
-- ==========================================
ALTER TABLE frameworks ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE frameworks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON frameworks;
CREATE POLICY tenant_isolation_policy ON frameworks
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: controls
-- ==========================================
ALTER TABLE controls ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE controls ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON controls;
CREATE POLICY tenant_isolation_policy ON controls
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: control_mappings
-- ==========================================
ALTER TABLE control_mappings ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE control_mappings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON control_mappings;
CREATE POLICY tenant_isolation_policy ON control_mappings
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: policies
-- ==========================================
ALTER TABLE policies ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE policies ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON policies;
CREATE POLICY tenant_isolation_policy ON policies
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: evidence
-- ==========================================
ALTER TABLE evidence ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE evidence ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON evidence;
CREATE POLICY tenant_isolation_policy ON evidence
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: assessments
-- ==========================================
ALTER TABLE assessments ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE assessments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON assessments;
CREATE POLICY tenant_isolation_policy ON assessments
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: documents
-- ==========================================
ALTER TABLE documents ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON documents;
CREATE POLICY tenant_isolation_policy ON documents
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: master_templates
-- ==========================================
ALTER TABLE master_templates ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE master_templates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON master_templates;
CREATE POLICY tenant_isolation_policy ON master_templates
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: context_issues
-- ==========================================
ALTER TABLE context_issues ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE context_issues ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON context_issues;
CREATE POLICY tenant_isolation_policy ON context_issues
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: interested_parties
-- ==========================================
ALTER TABLE interested_parties ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE interested_parties ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON interested_parties;
CREATE POLICY tenant_isolation_policy ON interested_parties
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: scope_documents
-- ==========================================
ALTER TABLE scope_documents ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE scope_documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON scope_documents;
CREATE POLICY tenant_isolation_policy ON scope_documents
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: processes
-- ==========================================
ALTER TABLE processes ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE processes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON processes;
CREATE POLICY tenant_isolation_policy ON processes
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: sub_processes
-- ==========================================
ALTER TABLE sub_processes ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE sub_processes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON sub_processes;
CREATE POLICY tenant_isolation_policy ON sub_processes
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: process_control_mapping
-- ==========================================
ALTER TABLE process_control_mapping ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE process_control_mapping ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON process_control_mapping;
CREATE POLICY tenant_isolation_policy ON process_control_mapping
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: requirement_master
-- ==========================================
ALTER TABLE requirement_master ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE requirement_master ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON requirement_master;
CREATE POLICY tenant_isolation_policy ON requirement_master
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: requirement_status
-- ==========================================
ALTER TABLE requirement_status ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE requirement_status ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON requirement_status;
CREATE POLICY tenant_isolation_policy ON requirement_status
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: compliance_settings
-- ==========================================
ALTER TABLE compliance_settings ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE compliance_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON compliance_settings;
CREATE POLICY tenant_isolation_policy ON compliance_settings
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- TABLE: cloud_resources
-- ==========================================
ALTER TABLE cloud_resources ADD COLUMN IF NOT EXISTS tenant_id UUID DEFAULT uuid_generate_v4();
ALTER TABLE cloud_resources ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON cloud_resources;
CREATE POLICY tenant_isolation_policy ON cloud_resources
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ==========================================
-- END OF SCRIPT
-- ==========================================
-- NOTES:
-- 1. Ensure your application sets "app.current_tenant" at the start of every transaction.
--    Example (Python/SQLAlchemy):
--    session.execute(text("SET app.current_tenant = :tenant_id"), {"tenant_id": user.tenant_id})
-- 2. If you have a Superuser/Admin who needs Global Access, consider creating a BYPASSRLS user 
--    or adding a permissive policy (e.g., OR current_setting('app.current_tenant') = 'admin').
