from app.services.ai_service import suggest_evidence
import json
import os

# Ensure API Key is loaded for script execution
from app.config import settings
import openai

if not settings.OPENAI_API_KEY:
    import os
    settings.OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

print("--- Testing Auditor Persona Logic ---")

# Simulate A.8.12 Data Leakage Prevention
result = suggest_evidence(
    title="A.8.12 Data Leakage Prevention",
    description="Data leakage prevention measures shall be applied to systems, networks and any other devices that process, store or transmit sensitive information.",
    category="Technical",
    control_id="A.8.12",
    regenerate=True # Force new generation
)

print("\n[EXPLANATION]:")
print(result.get("explanation"))


print("\n[REQUIREMENTS]:")
reqs = result.get("requirements", [])
verify_count = 0
source_correctness = True

for i, req in enumerate(reqs):
    name = req['name']
    source = req.get('source', 'N/A') # Note: The backend code maps result key to 'source' if missing but let's check raw or mapped
    # In ai_service, it just passes fields. Oh wait, ai_service maps keys:
    # "source": r.get("Source", "MANUAL") <-- It actually DOES NOT map Source in the snippet I saw earlier! 
    # Let me check the ai_service.py 'result mapping' section again.
    # Ah, I see:
    # final_requirements.append({
    #             "name": r.get("Requirement_Name", "Unknown Artifact"),
    #             ...
    
    print(f"{i+1}. {name} ({req['type']})")
    print(f"   Desc: {req['desc']}")
    print(f"   Guidance: {req['audit_guidance']}\n")
    
    if name.startswith("Verify"):
        verify_count += 1
    else:
        print(f"   FAIL: Name does not start with 'Verify'")

if len(reqs) == 6:
    print("SUCCESS: Exactly 6 requirements generated.")
else:
    print(f"FAIL: Generated {len(reqs)} requirements (Expected 6).")

if verify_count == len(reqs) and len(reqs) > 0:
    print("SUCCESS: All requirements start with 'Verify'.")
else:
    print(f"FAIL: Only {verify_count}/{len(reqs)} start with 'Verify'.")

if "Generated by AI" in result.get("explanation", ""):
    print("FAIL: Explanation contains forbidden phrase 'Generated by AI'.")
else:
    print("SUCCESS: Explanation is clean.")

