ISO_CONTROLS_DATA = [
    {
        "control_id": "4.1",
        "title": "Understanding the organization and its context",
        "description": "The organization shall determine external and internal issues that are relevant to its purpose and that affect its ability to achieve the intended outcome(s) of its information security management system.",
        "category": "Governance",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 4: Context of the Organization",
    },
    {
        "control_id": "4.2",
        "title": "Understanding the needs and expectations of interested parties",
        "description": "The organization shall determine: a) interested parties that are relevant to the information security management system; and b) the requirements of these interested parties relevant to information security.",
        "category": "Governance",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 4: Context of the Organization",
    },
    {
        "control_id": "4.3",
        "title": "Determining the scope of the information security management system",
        "description": "The organization shall determine the boundaries and applicability of the information security management system to establish its scope.",
        "category": "Governance",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 4: Context of the Organization",
    },
    {
        "control_id": "4.4",
        "title": "Information security management system",
        "description": "The organization shall establish, implement, maintain and continually improve an information security management system, in accordance with the requirements of this document.",
        "category": "Governance",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 4: Context of the Organization",
    },
    {
        "control_id": "5.1",
        "title": "Leadership and commitment",
        "description": "Top management shall demonstrate leadership and commitment with respect to the information security management system.",
        "category": "Governance",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 5: Leadership",
    },
    {
        "control_id": "5.2",
        "title": "Policy",
        "description": "Top management shall establish an information security policy.",
        "category": "Governance",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 5: Leadership",
    },
    {
        "control_id": "5.3",
        "title": "Organizational roles, responsibilities and authorities",
        "description": "Top management shall ensure that the responsibilities and authorities for roles relevant to information security are assigned and communicated.",
        "category": "Governance",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 5: Leadership",
    },
    {
        "control_id": "6.1.1",
        "title": "General (Actions to address risks and opportunities)",
        "description": "When planning for the information security management system, the organization shall consider the issues referred to in 4.1 and the requirements referred to in 4.2 and determine the risks and opportunities that need to be addressed.",
        "category": "Risk Management",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 6: Planning",
    },
    {
        "control_id": "6.1.2",
        "title": "Information security risk assessment",
        "description": "The organization shall define and apply an information security risk assessment process.",
        "category": "Risk Management",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 6: Planning",
    },
    {
        "control_id": "6.1.3",
        "title": "Information security risk treatment",
        "description": "The organization shall define and apply an information security risk treatment process.",
        "category": "Risk Management",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 6: Planning",
    },
    {
        "control_id": "6.2",
        "title": "Information security objectives and planning to achieve them",
        "description": "The organization shall establish information security objectives at relevant functions and levels.",
        "category": "Governance",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 6: Planning",
    },
    {
        "control_id": "6.3",
        "title": "Planning of changes",
        "description": "When the organization determines the need for changes to the information security management system, the changes shall be carried out in a planned manner.",
        "category": "Governance",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Clause 6: Planning",
    },
    {
        "control_id": "7.1",
        "title": "Resources",
        "description": "The organization shall determine and provide the resources needed for the establishment, implementation, maintenance and continual improvement of the information security management system.",
        "category": "Governance",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 7: Support",
    },
    {
        "control_id": "7.2",
        "title": "Competence",
        "description": "The organization shall determine the necessary competence of person(s) doing work under its control.",
        "category": "HR Security",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 7: Support",
    },
    {
        "control_id": "7.3",
        "title": "Awareness",
        "description": "Persons doing work under the organization's control shall be aware of the information security policy.",
        "category": "HR Security",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 7: Support",
    },
    {
        "control_id": "7.4",
        "title": "Communication",
        "description": "The organization shall determine the need for internal and external communications relevant to the information security management system.",
        "category": "Incident & Resilience",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Clause 7: Support",
    },
    {
        "control_id": "7.5.1",
        "title": "Documented information - General",
        "description": "The organization's information security management system shall include: a) documented information required by this document; and b) documented information determined by the organization as being necessary for the effectiveness of the information security management system.",
        "category": "Governance",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Clause 7: Support",
    },
    {
        "control_id": "7.5.2",
        "title": "Creating and updating",
        "description": "When creating and updating documented information the organization shall ensure appropriate: a) identification and description (e.g. a title, date, author, or reference number); b) format (e.g. language, software version, graphics) and media (e.g. paper, electronic); and c) review and approval for suitability and adequacy.",
        "category": "Governance",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Clause 7: Support",
    },
    {
        "control_id": "7.5.3",
        "title": "Control of documented information",
        "description": "Documented information required by the information security management system and by this document shall be controlled to ensure: a) it is available and suitable for use, where and when it is needed; and b) it is adequately protected (e.g. from loss of confidentiality, improper use, or loss of integrity).",
        "category": "Governance",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 7: Support",
    },
    {
        "control_id": "8.1",
        "title": "Operational planning and control",
        "description": "The organization shall plan, implement and control the processes needed to meet information security requirements.",
        "category": "Risk Management",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 8: Operation",
    },
    {
        "control_id": "8.2",
        "title": "Information security risk assessment",
        "description": "The organization shall perform information security risk assessments at planned intervals.",
        "category": "Risk Management",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 8: Operation",
    },
    {
        "control_id": "8.3",
        "title": "Information security risk treatment",
        "description": "The organization shall implement the information security risk treatment plan.",
        "category": "Risk Management",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 8: Operation",
    },
    {
        "control_id": "9.1",
        "title": "Monitoring, measurement, analysis and evaluation",
        "description": "The organization shall evaluate the information security performance and the effectiveness of the information security management system.",
        "category": "Performance Evaluation",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 9: Performance Evaluation",
    },
    {
        "control_id": "9.2.1",
        "title": "Internal audit - General",
        "description": "The organization shall conduct internal audits at planned intervals to provide information on whether the information security management system: a) conforms to 1) the organization’s own requirements for its information security management system; 2) the requirements of this document; b) is effectively implemented and maintained.",
        "category": "Performance Evaluation",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 9: Performance Evaluation",
    },
    {
        "control_id": "9.2.2",
        "title": "Internal audit programme",
        "description": "The organization shall plan, establish, implement and maintain an audit programme(s), including the frequency, methods, responsibilities, planning requirements and reporting. The audit programme(s) shall take into consideration the importance of the processes concerned and the results of previous audits.",
        "category": "Performance Evaluation",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 9: Performance Evaluation",
    },
    {
        "control_id": "9.3.1",
        "title": "Management review - General",
        "description": "Top management shall review the organization's information security management system at planned intervals to ensure its continuing suitability, adequacy and effectiveness.",
        "category": "Performance Evaluation",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 9: Performance Evaluation",
    },
    {
        "control_id": "9.3.2",
        "title": "Management review inputs",
        "description": "The management review shall include consideration of: a) the status of actions from previous management reviews; b) changes in external and internal issues that are relevant to the information security management system; c) feedback on the information security performance, including trends in...",
        "category": "Performance Evaluation",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 9: Performance Evaluation",
    },
    {
        "control_id": "9.3.3",
        "title": "Management review results",
        "description": "The results of the management review shall include decisions related to continual improvement opportunities and any needs for changes to the information security management system.",
        "category": "Performance Evaluation",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 9: Performance Evaluation",
    },
    {
        "control_id": "10.1",
        "title": "Continual improvement",
        "description": "The organization shall continually improve the suitability, adequacy and effectiveness of the information security management system.",
        "category": "Improvement",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 10: Improvement",
    },
    {
        "control_id": "10.2",
        "title": "Nonconformity and corrective action",
        "description": "When a nonconformity occurs, the organization shall react to the nonconformity and take action.",
        "category": "Improvement",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Clause 10: Improvement",
    },
    {
        "control_id": "A.5.1",
        "title": "Policies for information security",
        "description": "Information security policy and topic-specific policies shall be defined, approved by management, published, communicated to and acknowledged by relevant personnel and relevant interested parties, and reviewed at planned intervals and if significant changes occur.",
        "category": "Governance",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.2",
        "title": "Information security roles and responsibilities",
        "description": "Information security roles and responsibilities shall be defined and allocated according to the organization needs.",
        "category": "Governance",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.3",
        "title": "Segregation of duties",
        "description": "Conflicting duties and conflicting areas of responsibility shall be segregated.",
        "category": "Governance",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.4",
        "title": "Management responsibilities",
        "description": "Management shall require all personnel to apply information security in accordance with the established information security policy, topic-specific policies and procedures of the organization.",
        "category": "Governance",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.5",
        "title": "Contact with authorities",
        "description": "The organization shall establish and maintain contact with relevant authorities.",
        "category": "Governance",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.6",
        "title": "Contact with special interest groups",
        "description": "The organization shall establish and maintain contact with special interest groups or other specialist security forums and professional associations.",
        "category": "Governance",
        "priority": "low",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.7",
        "title": "Threat intelligence",
        "description": "Information relating to information security threats shall be collected and analysed to produce threat intelligence.",
        "category": "Threat Intel",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.8",
        "title": "Information security in project management",
        "description": "Information security shall be integrated into project management.",
        "category": "Governance",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.9",
        "title": "Inventory of information and other associated assets",
        "description": "An inventory of information and other associated assets, including owners, shall be developed and maintained.",
        "category": "Asset Management",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.10",
        "title": "Acceptable use of information and other associated assets",
        "description": "Rules for the acceptable use and procedures for handling information and other associated assets shall be identified, documented and implemented.",
        "category": "Asset Management",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.11",
        "title": "Return of assets",
        "description": "Personnel and other interested parties as appropriate shall return all of the organizational assets in their possession upon change or termination of their employment, contract or agreement.",
        "category": "Asset Management",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.12",
        "title": "Classification of information",
        "description": "Information shall be classified according to the information security needs of the organization based on confidentiality, integrity, availability and relevant interested party requirements.",
        "category": "Asset Management",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.13",
        "title": "Labelling of information",
        "description": "An appropriate set of procedures for information labelling shall be developed and implemented in accordance with the information classification scheme adopted by the organization.",
        "category": "Asset Management",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.14",
        "title": "Information transfer",
        "description": "Information transfer rules, procedures, or agreements shall be in place for all types of transfer facilities within the organization and between the organization and other parties.",
        "category": "Network Security",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.15",
        "title": "Access control",
        "description": "Rules to control physical and logical access to information and other associated assets shall be established and implemented based on business and information security requirements.",
        "category": "Access Control (IAM)",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.16",
        "title": "Identity management",
        "description": "The full life cycle of identities shall be managed.",
        "category": "Access Control (IAM)",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.17",
        "title": "Authentication information",
        "description": "Allocation and management of authentication information shall be controlled by a management process, including advising personnel on appropriate handling of authentication information.",
        "category": "Access Control (IAM)",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.18",
        "title": "Access rights",
        "description": "Access rights to information and other associated assets shall be provisioned, reviewed, modified and removed in accordance with the organization's topic-specific policy on and rules for access control.",
        "category": "Access Control (IAM)",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.19",
        "title": "Information security in supplier relationships",
        "description": "Processes and procedures shall be defined and implemented to manage the information security risks associated with the use of supplier's products or services.",
        "category": "Supplier Mgmt",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.20",
        "title": "Addressing information security within supplier agreements",
        "description": "Relevant information security requirements shall be established and agreed with each supplier based on the type of supplier relationship.",
        "category": "Supplier Mgmt",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.21",
        "title": "Managing information security in the ICT supply chain",
        "description": "Processes and procedures shall be defined and implemented to manage the information security risks associated with the ICT products and services supply chain.",
        "category": "Supplier Mgmt",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.22",
        "title": "Monitoring, review and change management of supplier services",
        "description": "The organization shall regularly monitor, review, evaluate and manage change in supplier information security practices and service delivery.",
        "category": "Supplier Mgmt",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.23",
        "title": "Information security for use of cloud services",
        "description": "Processes for acquisition, use, management and exit from cloud services shall be established in accordance with the organization's information security requirements.",
        "category": "Supplier Mgmt",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.24",
        "title": "Information security incident management planning and preparation",
        "description": "The organization shall plan and prepare for managing information security incidents by defining, establishing and communicating information security incident management processes, roles and responsibilities.",
        "category": "Incident & Resilience",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.25",
        "title": "Assessment and decision on information security events",
        "description": "The organization shall assess information security events and decide if they are to be categorized as information security incidents.",
        "category": "Incident & Resilience",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.26",
        "title": "Response to information security incidents",
        "description": "Information security incidents shall be responded to in accordance with the documented procedures.",
        "category": "Incident & Resilience",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.27",
        "title": "Learning from information security incidents",
        "description": "Knowledge gained from information security incidents shall be used to strengthen and improve the information security controls.",
        "category": "Incident & Resilience",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.28",
        "title": "Collection of evidence",
        "description": "The organization shall establish and implement procedures for the identification, collection, acquisition and preservation of evidence related to information security events.",
        "category": "Incident & Resilience",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.29",
        "title": "Information security during disruption",
        "description": "The organization shall plan how to maintain information security at an appropriate level during disruption.",
        "category": "Incident & Resilience",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.30",
        "title": "ICT readiness for business continuity",
        "description": "ICT readiness shall be planned, implemented, maintained and tested based on business continuity objectives and ICT continuity requirements.",
        "category": "Incident & Resilience",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.31",
        "title": "Legal, statutory, regulatory and contractual requirements",
        "description": "Legal, statutory, regulatory and contractual requirements relevant to information security and the organization's approach to meet these requirements shall be identified, documented and kept up to date.",
        "category": "Legal & Compliance",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.32",
        "title": "Intellectual property rights",
        "description": "The organization shall implement appropriate procedures to protect intellectual property rights.",
        "category": "Legal & Compliance",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.33",
        "title": "Protection of records",
        "description": "Records shall be protected from loss, destruction, falsification, unauthorized access and unauthorized release.",
        "category": "Legal & Compliance",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.34",
        "title": "Privacy and protection of PII",
        "description": "The organization shall identify and meet the requirements regarding the preservation of privacy and protection of PII according to applicable laws and regulations and contractual requirements.",
        "category": "Legal & Compliance",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.35",
        "title": "Independent review of information security",
        "description": "The organization's approach to managing information security and its implementation including people, processes and technologies shall be reviewed independently at planned intervals, or when significant changes occur.",
        "category": "Performance Evaluation",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.36",
        "title": "Compliance with policies, rules and standards for information security",
        "description": "Compliance with the organization's information security policy, topic-specific policies, rules and standards shall be regularly reviewed.",
        "category": "Legal & Compliance",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.5.37",
        "title": "Documented operating procedures",
        "description": "Operating procedures for information processing facilities shall be documented and made available to personnel who need them.",
        "category": "Governance",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.5: Organizational Controls",
    },
    {
        "control_id": "A.6.1",
        "title": "Screening",
        "description": "Background verification checks on all candidates to become personnel shall be carried out prior to joining the organization and on an ongoing basis taking into consideration applicable laws, regulations and ethics and be proportional to the business requirements, the classification of the information to be accessed and the perceived risks.",
        "category": "HR Security",
        "priority": "high",
        "classification": "HYBRID",
        "domain": "Annex A.6: People Controls",
    },
    {
        "control_id": "A.6.2",
        "title": "Terms and conditions of employment",
        "description": "The employment contractual agreements shall state the personnel's and the organization's responsibilities for information security.",
        "category": "HR Security",
        "priority": "high",
        "classification": "HYBRID",
        "domain": "Annex A.6: People Controls",
    },
    {
        "control_id": "A.6.3",
        "title": "Information security awareness, education and training",
        "description": "Personnel of the organization and relevant interested parties shall receive appropriate information security awareness, education and training and regular updates of the organization's information security policy, topic-specific policies and procedures, as relevant for their job function.",
        "category": "HR Security",
        "priority": "high",
        "classification": "HYBRID",
        "domain": "Annex A.6: People Controls",
    },
    {
        "control_id": "A.6.4",
        "title": "Disciplinary process",
        "description": "A disciplinary process shall be formalized and communicated to take actions against personnel and other relevant interested parties who have committed an information security policy violation.",
        "category": "HR Security",
        "priority": "medium",
        "classification": "HYBRID",
        "domain": "Annex A.6: People Controls",
    },
    {
        "control_id": "A.6.5",
        "title": "Responsibilities after termination or change of employment",
        "description": "Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, enforced and communicated to relevant personnel and other interested parties.",
        "category": "HR Security",
        "priority": "high",
        "classification": "HYBRID",
        "domain": "Annex A.6: People Controls",
    },
    {
        "control_id": "A.6.6",
        "title": "Confidentiality or non-disclosure agreements",
        "description": "Confidentiality or non-disclosure agreements reflecting the organization's needs for the protection of information shall be identified, documented, regularly reviewed and signed by personnel and other relevant interested parties.",
        "category": "HR Security",
        "priority": "high",
        "classification": "HYBRID",
        "domain": "Annex A.6: People Controls",
    },
    {
        "control_id": "A.6.7",
        "title": "Remote working",
        "description": "Security measures shall be implemented when personnel are working remotely to protect information accessed, processed or stored outside the organization's premises.",
        "category": "HR Security",
        "priority": "high",
        "classification": "HYBRID",
        "domain": "Annex A.6: People Controls",
    },
    {
        "control_id": "A.6.8",
        "title": "Information security event reporting",
        "description": "The organization shall provide a mechanism for personnel to report observed or suspected information security events through appropriate channels in a timely manner.",
        "category": "HR Security",
        "priority": "high",
        "classification": "HYBRID",
        "domain": "Annex A.6: People Controls",
    },
    {
        "control_id": "A.7.1",
        "title": "Physical security perimeters",
        "description": "Security perimeters shall be defined and used to protect areas that contain information and other associated assets.",
        "category": "Physical Security",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.7: Physical Controls",
    },
    {
        "control_id": "A.7.2",
        "title": "Physical entry",
        "description": "Secure areas shall be protected by appropriate entry controls and access points.",
        "category": "Physical Security",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.7: Physical Controls",
    },
    {
        "control_id": "A.7.3",
        "title": "Securing offices, rooms and facilities",
        "description": "Physical security for offices, rooms and facilities shall be designed and implemented.",
        "category": "Physical Security",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.7: Physical Controls",
    },
    {
        "control_id": "A.7.4",
        "title": "Physical security monitoring",
        "description": "Premises shall be continuously monitored for unauthorized physical access.",
        "category": "Physical Security",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.7: Physical Controls",
    },
    {
        "control_id": "A.7.5",
        "title": "Protecting against physical and environmental threats",
        "description": "Protection against physical and environmental threats, such as natural disasters and other intentional or unintentional physical threats to infrastructure shall be designed and implemented.",
        "category": "Physical Security",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.7: Physical Controls",
    },
    {
        "control_id": "A.7.6",
        "title": "Working in secure areas",
        "description": "Security measures for working in secure areas shall be designed and implemented.",
        "category": "Physical Security",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.7: Physical Controls",
    },
    {
        "control_id": "A.7.7",
        "title": "Clear desk and clear screen",
        "description": "Clear desk rules for papers and removable storage media and clear screen rules for information processing facilities shall be defined and appropriately enforced.",
        "category": "Physical Security",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.7: Physical Controls",
    },
    {
        "control_id": "A.7.8",
        "title": "Equipment siting and protection",
        "description": "Equipment shall be sited securely and protected.",
        "category": "Physical Security",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.7: Physical Controls",
    },
    {
        "control_id": "A.7.9",
        "title": "Security of assets off-premises",
        "description": "Off-site assets shall be protected.",
        "category": "Physical Security",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.7: Physical Controls",
    },
    {
        "control_id": "A.7.10",
        "title": "Storage media",
        "description": "Storage media shall be managed through their life cycle of acquisition, use, transportation and disposal in accordance with the organization's classification scheme and handling requirements.",
        "category": "Asset Management",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.7: Physical Controls",
    },
    {
        "control_id": "A.7.11",
        "title": "Supporting utilities",
        "description": "Information processing facilities shall be protected from power failures and other disruptions caused by failures in supporting utilities.",
        "category": "Physical Security",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.7: Physical Controls",
    },
    {
        "control_id": "A.7.12",
        "title": "Cabling security",
        "description": "Cables carrying power, data or supporting information services shall be protected from interception, interference or damage.",
        "category": "Physical Security",
        "priority": "low",
        "classification": "MANUAL",
        "domain": "Annex A.7: Physical Controls",
    },
    {
        "control_id": "A.7.13",
        "title": "Equipment maintenance",
        "description": "Equipment shall be maintained correctly to ensure availability, integrity and confidentiality of information.",
        "category": "Physical Security",
        "priority": "medium",
        "classification": "MANUAL",
        "domain": "Annex A.7: Physical Controls",
    },
    {
        "control_id": "A.7.14",
        "title": "Secure disposal or re-use of equipment",
        "description": "Items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten prior to disposal or re-use.",
        "category": "Asset Management",
        "priority": "high",
        "classification": "MANUAL",
        "domain": "Annex A.7: Physical Controls",
    },
    {
        "control_id": "A.8.1",
        "title": "User endpoint devices",
        "description": "Information stored on, processed by or accessible via user endpoint devices shall be protected.",
        "category": "Operations",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.2",
        "title": "Privileged access rights",
        "description": "The allocation and use of privileged access rights shall be restricted and managed.",
        "category": "Access Control (IAM)",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.3",
        "title": "Information access restriction",
        "description": "Access to information and other associated assets shall be restricted in accordance with the established topic-specific policy on access control.",
        "category": "Access Control (IAM)",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.4",
        "title": "Access to source code",
        "description": "Read and write access to source code, development tools and software libraries shall be appropriately managed.",
        "category": "Access Control (IAM)",
        "priority": "medium",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.5",
        "title": "Secure authentication",
        "description": "Secure authentication technologies and procedures shall be implemented based on information access restrictions and the topic-specific policy on access control.",
        "category": "Access Control (IAM)",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.6",
        "title": "Capacity management",
        "description": "The use of resources shall be monitored and adjusted in line with current and expected capacity requirements.",
        "category": "Capacity Management",
        "priority": "medium",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.7",
        "title": "Protection against malware",
        "description": "Protection against malware shall be implemented and supported by appropriate user awareness.",
        "category": "Operations",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.8",
        "title": "Management of technical vulnerabilities",
        "description": "Information about technical vulnerabilities of information systems in use shall be obtained, the organization's exposure to such vulnerabilities shall be evaluated and appropriate measures shall be taken.",
        "category": "Vulnerability Management",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.9",
        "title": "Configuration management",
        "description": "Configurations, including security configurations, of hardware, software, services and networks shall be established, documented, implemented, monitored and reviewed.",
        "category": "Configuration Management",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.10",
        "title": "Information deletion",
        "description": "Information stored in information systems, devices or in any other storage media shall be deleted when no longer required.",
        "category": "Operations",
        "priority": "medium",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.11",
        "title": "Data masking",
        "description": "Data masking shall be used in accordance with the organization's topic-specific policy on access control and other related topic-specific policies, and business requirements, taking applicable legislation into consideration.",
        "category": "Cryptography",
        "priority": "medium",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.12",
        "title": "Data leakage prevention",
        "description": "Data leakage prevention measures shall be applied to systems, networks and any other devices that process, store or transmit sensitive information.",
        "category": "Operations",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.13",
        "title": "Information backup",
        "description": "Backup copies of information, software and systems shall be maintained and regularly tested in accordance with the agreed topic-specific policy on backup.",
        "category": "Backup Management",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.14",
        "title": "Redundancy of information processing facilities",
        "description": "Information processing facilities shall be implemented with redundancy sufficient to meet availability requirements.",
        "category": "Incident & Resilience",
        "priority": "medium",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.15",
        "title": "Logging",
        "description": "Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed.",
        "category": "Logging & Monitoring",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.16",
        "title": "Monitoring activities",
        "description": "Networks, systems and applications shall be monitored for anomalous behaviour and appropriate actions taken to evaluate potential information security incidents.",
        "category": "Logging & Monitoring",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.17",
        "title": "Clock synchronization",
        "description": "The clocks of information processing systems used by the organization shall be synchronized to approved time sources.",
        "category": "Clock Synchronization",
        "priority": "low",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.18",
        "title": "Use of privileged utility programs",
        "description": "The use of utility programs that can be capable of overriding system and application controls shall be restricted and tightly controlled.",
        "category": "Operations",
        "priority": "medium",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.20",
        "title": "Networks security",
        "description": "Networks and network devices shall be secured, managed and controlled to protect information in systems and applications.",
        "category": "Network Security",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.21",
        "title": "Security of network services",
        "description": "Security mechanisms, service levels and service requirements of network services shall be identified, implemented and monitored.",
        "category": "Network Security",
        "priority": "medium",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.22",
        "title": "Segregation of networks",
        "description": "Groups of information services, users and information systems shall be segregated in the organization's networks.",
        "category": "Network Security",
        "priority": "medium",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.23",
        "title": "Web filtering",
        "description": "Access to external websites shall be managed to reduce exposure to malicious content.",
        "category": "Network Security",
        "priority": "medium",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.24",
        "title": "Use of cryptography",
        "description": "Rules for the effective use of cryptography, including cryptographic key management, shall be defined and implemented.",
        "category": "Cryptography",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.25",
        "title": "Secure development life cycle",
        "description": "Rules for the secure development of software and systems shall be established and applied.",
        "category": "SDLC (Development)",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.26",
        "title": "Application security requirements",
        "description": "Information security requirements shall be identified, specified and approved when developing or acquiring applications.",
        "category": "SDLC (Development)",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.27",
        "title": "Secure system architecture and engineering principles",
        "description": "Principles for engineering secure systems shall be established, documented, maintained and applied to any information system development activities.",
        "category": "SDLC (Development)",
        "priority": "medium",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.28",
        "title": "Secure coding",
        "description": "Secure coding principles shall be applied to software development.",
        "category": "SDLC (Development)",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.29",
        "title": "Security testing in development and acceptance",
        "description": "Security testing processes shall be defined and implemented in the development life cycle.",
        "category": "SDLC (Development)",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.30",
        "title": "Outsourced development",
        "description": "The organization shall direct, monitor and review the activities related to outsourced system development.",
        "category": "SDLC (Development)",
        "priority": "medium",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.31",
        "title": "Separation of development, test and production environments",
        "description": "Development, testing and production environments shall be separated and secured.",
        "category": "SDLC (Development)",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.32",
        "title": "Change management",
        "description": "Changes to information processing facilities and information systems shall be subject to change management procedures.",
        "category": "SDLC (Development)",
        "priority": "high",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.33",
        "title": "Test information",
        "description": "Test information shall be appropriately selected, protected and managed.",
        "category": "SDLC (Development)",
        "priority": "medium",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.34",
        "title": "Protection of information systems during audit testing",
        "description": "Audit tests and other assurance activities involving assessment of operational systems shall be planned and agreed between the tester and appropriate management.",
        "category": "Legal & Compliance",
        "priority": "low",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
    {
        "control_id": "A.8.19",
        "title": "Installation of software on operational systems",
        "description": "Procedures and measures shall be implemented to securely manage software installation on operational systems.",
        "category": "Operations",
        "priority": "medium",
        "classification": "AUTO",
        "domain": "Annex A.8: Technological Controls",
    },
]
