
SOC2_CONTROLS_DATA = [
    # Common Criteria (Security)
    {"control_id": "CC1.1", "title": "COSO Principle 1: Human Resources", "description": "The entity demonstrates a commitment to integrity and ethical values.", "category": "Governance", "priority": "high", "domain": "CC1: Control Environment"},
    {"control_id": "CC1.2", "title": "COSO Principle 2: Board of Directors", "description": "The board of directors demonstrates independence from management and exercises oversight of the development and performance of internal control.", "category": "Governance", "priority": "high", "domain": "CC1: Control Environment"},
    {"control_id": "CC1.3", "title": "COSO Principle 3: Management Structures", "description": "Management establishes, with board oversight, structures, reporting lines, and appropriate authorities and responsibilities in the pursuit of objectives.", "category": "Governance", "priority": "medium", "domain": "CC1: Control Environment"},
    {"control_id": "CC1.4", "title": "COSO Principle 4: Human Resources", "description": "The entity demonstrates a commitment to attract, develop, and retain competent individuals in alignment with objectives.", "category": "HR Security", "priority": "high", "domain": "CC1: Control Environment"},
    {"control_id": "CC1.5", "title": "COSO Principle 5: Accountability", "description": "The entity holds individuals accountable for their internal control responsibilities in the pursuit of objectives.", "category": "HR Security", "priority": "high", "domain": "CC1: Control Environment"},

    {"control_id": "CC2.1", "title": "COSO Principle 6: Communication", "description": "The entity obtains or generates and uses relevant, quality information to support the functioning of internal control.", "category": "Governance", "priority": "medium", "domain": "CC2: Communication & Information"},
    {"control_id": "CC2.2", "title": "COSO Principle 7: Internal Communication", "description": "The entity communicates information internally, including objectives and responsibilities for internal control, necessary to support the functioning of internal control.", "category": "Governance", "priority": "medium", "domain": "CC2: Communication & Information"},
    {"control_id": "CC2.3", "title": "COSO Principle 8: External Communication", "description": "The entity communicates with external parties regarding matters affecting the functioning of internal control.", "category": "Governance", "priority": "medium", "domain": "CC2: Communication & Information"},

    {"control_id": "CC3.1", "title": "COSO Principle 9: Risk Mitigation", "description": "The entity specifies objectives with sufficient clarity to enable the identification and assessment of risks relating to objectives.", "category": "Risk Management", "priority": "high", "domain": "CC3: Risk Assessment"},
    {"control_id": "CC3.2", "title": "COSO Principle 10: Fraud Risk", "description": "The entity identifies risks to the achievement of its objectives across the entity and analyzes risks as a basis for determining how the risks should be managed.", "category": "Risk Management", "priority": "high", "domain": "CC3: Risk Assessment"},
    {"control_id": "CC3.3", "title": "COSO Principle 11: Significant Change", "description": "The entity considers the potential for fraud in assessing risks to the achievement of objectives.", "category": "Risk Management", "priority": "high", "domain": "CC3: Risk Assessment"},
    {"control_id": "CC3.4", "title": "COSO Principle 12: Monitoring", "description": "The entity identifies and assesses changes that could significantly impact the system of internal control.", "category": "Risk Management", "priority": "high", "domain": "CC3: Risk Assessment"},

    {"control_id": "CC4.1", "title": "COSO Principle 13: Evaluation", "description": "The entity selects and develops control activities that contribute to the mitigation of risks to the achievement of objectives to acceptable levels.", "category": "Governance", "priority": "high", "domain": "CC4: Monitoring Activities"},
    {"control_id": "CC4.2", "title": "COSO Principle 14: Deficiencies", "description": "The entity selects and develops general control activities over technology to support the achievement of objectives.", "category": "Governance", "priority": "high", "domain": "CC4: Monitoring Activities"},

    {"control_id": "CC5.1", "title": "COSO Principle 15: Evaluation", "description": "The entity deploys control activities through policies that establish what is expected and procedures that put policies into action.", "category": "Governance", "priority": "medium", "domain": "CC5: Control Activities"},
    {"control_id": "CC5.2", "title": "COSO Principle 16: Communication", "description": "The entity selects, develops, and performs ongoing and/or separate evaluations to ascertain whether the components of internal control are present and functioning.", "category": "Governance", "priority": "medium", "domain": "CC5: Control Activities"},
    {"control_id": "CC5.3", "title": "COSO Principle 17: Deficiencies", "description": "The entity evaluates and communicates internal control deficiencies in a timely manner to those parties responsible for taking corrective action, including senior management and the board of directors, as appropriate.", "category": "Governance", "priority": "high", "domain": "CC5: Control Activities"},

    # Logical and Physical Access Controls
    {"control_id": "CC6.1", "title": "Logical Access Security", "description": "The entity implements logical access security software, infrastructure, and architectures over protected information assets to protect them from security events to meet the entity's objectives.", "category": "Access Control (IAM)", "priority": "high", "domain": "CC6: Logical and Physical Access Controls"},
    {"control_id": "CC6.2", "title": "User Registration", "description": "The entity manages the user registration process and method to log in (authentication) for users.", "category": "Access Control (IAM)", "priority": "high", "domain": "CC6: Logical and Physical Access Controls"},
    {"control_id": "CC6.3", "title": "Authorization", "description": "The entity authorizes requests to create, modify, or delete protected information assets.", "category": "Access Control (IAM)", "priority": "high", "domain": "CC6: Logical and Physical Access Controls"},
    {"control_id": "CC6.4", "title": "Physical Access", "description": "The entity restricts physical access to facilities and protected information assets to authorized personnel.", "category": "Physical Security", "priority": "high", "domain": "CC6: Logical and Physical Access Controls"},
    {"control_id": "CC6.5", "title": "Disposal of Assets", "description": "The entity discontinues logical and physical protections over physical assets only after the ability to read or recover data and software from those assets has been diminished and is no longer required to meet the entity’s objectives.", "category": "Asset Management", "priority": "medium", "domain": "CC6: Logical and Physical Access Controls"},
    {"control_id": "CC6.6", "title": "Virtualization Security", "description": "The entity implements logical access security measures to protect against threats from sources outside its system boundaries.", "category": "Network Security", "priority": "high", "domain": "CC6: Logical and Physical Access Controls"},
    {"control_id": "CC6.7", "title": "Data Transmission", "description": "The entity restricts the transmission, movement, and removal of information to authorized internal and external users and processes, and protects it during transmission, movement, or removal.", "category": "Network Security", "priority": "high", "domain": "CC6: Logical and Physical Access Controls"},
    {"control_id": "CC6.8", "title": "Malicious Code", "description": "The entity implements controls to prevent or detect and act upon the introduction of malicious software.", "category": "Endpoint Security", "priority": "high", "domain": "CC6: Logical and Physical Access Controls"},

    # System Operations
    {"control_id": "CC7.1", "title": "Detection of Anomalies", "description": "The entity uses detection and monitoring procedures to identify (1) changes to configurations that result in the introduction of new vulnerabilities, and (2) susceptibilities to newly discovered vulnerabilities.", "category": "Incident & Resilience", "priority": "high", "domain": "CC7: System Operations"},
    {"control_id": "CC7.2", "title": "Monitoring", "description": "The entity monitors system components and the operation of those components for anomalies that are indicative of malicious acts, natural disasters, and errors affecting the entity's ability to meet its objectives; anomalies are analyzed to determine whether they represent security events.", "category": "Incident & Resilience", "priority": "high", "domain": "CC7: System Operations"},
    {"control_id": "CC7.3", "title": "Incident Response", "description": "The entity evaluates security events to determine whether they could or have resulted in a failure of the entity to meet its objectives (security incidents) and, if so, takes actions to respond to the security incident.", "category": "Incident & Resilience", "priority": "high", "domain": "CC7: System Operations"},
    {"control_id": "CC7.4", "title": "Incident Containment", "description": "The entity responds to identified security incidents by executing a defined incident response program to understand, contain, remediate, and communicate security incidents, as appropriate.", "category": "Incident & Resilience", "priority": "high", "domain": "CC7: System Operations"},
    {"control_id": "CC7.5", "title": "Recovery", "description": "The entity identifies, develops, and implements activities to recover from identified security incidents.", "category": "Incident & Resilience", "priority": "high", "domain": "CC7: System Operations"},

    # Change Management
    {"control_id": "CC8.1", "title": "Change Management", "description": "The entity authorizes, designs, develops or acquires, configures, documents, tests, approves, and implements changes to infrastructure, data, software, and procedures to meet its objectives.", "category": "SDLC / Change Mgmt", "priority": "high", "domain": "CC8: Change Management"},

    # Risk Mitigation
    {"control_id": "CC9.1", "title": "Risk Mitigation", "description": "The entity identifies, selects, and develops risk mitigation activities for risks arising from potential business disruptions.", "category": "Risk Management", "priority": "high", "domain": "CC9: Risk Mitigation"},
    {"control_id": "CC9.2", "title": "Vendor Management", "description": "The entity assesses and manages risks associated with vendors and business partners.", "category": "Supplier Mgmt", "priority": "high", "domain": "CC9: Risk Mitigation"},

]
